version: "3.7"


services:

    phpinfo:
        image: priorist/phpinfo
        ports:
            - 80:80
        cap_drop:
            - ALL
        cap_add:
            - SETGID
            - SETUID
            - DAC_OVERRIDE
            - CHOWN
            - NET_BIND_SERVICE
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "10"
        labels:
            com.daimler.description: "Return contents of phpinfo()."
